
Introduce the chapter to the reader
* take the strands from the last chapter, and show them braided together
* in this chapter, you'll learn .... OR ok we're done looking at that, now let's xxx
* Tie the chapter to the goals of the book, and weave in the larger themes
* perspective, philosophy, what we'll be working, a bit of repositioning, a bit opinionated, a bit personal.


The stakeholders' opinions are the data; the subject under vote is the context; the room and time define the arena of computation; and the decision is synthesized according to the relevant organizational bylaws. 

Large portions of the playbook remain applicable but need extra machinery to succeed; 


Once you start thinking in terms of context
One could also hold the presidential election by directing supporters of one candidate to stand in a certain wide-open portion of Kansas, and supporters of the other candidate to stand in a similar portion of Iowa -- allowing a satellite photo and image 


=== Chapter Doneness: B

* _Introduction_: exists, lots of extra stuff, not readable
* _description of map phase_: good
* _demonstration hadoop job_
* _Chimpanzee and Elephant translate Shakespeare_
* _description of mapper phase_
* _how to run a Hadoop job_
* _Seeing your job's progress and output_
* _Sidebar: What's fast at high scale_
* _Overview of the HDFS_


This chapter and the next couple will see some reshuffling to give the following narrative flow:

1. (first chapter)
2. (this one) Here's how to use hadoop
3. Here's your first map/reduce jobs, and how data moves around behind the scenes
4. Pig lets you work with whole datasets, not record-by-record
5. The core analytic patterns of Hadoop, as Pig scripts and as Wukong map/reduce scripts

=== Pardon this digression-laden introduction

You can think of Hadoop's processing model in a few ways

The first part of this book will introduce the Hadoop toolset.

- The centerpiece of the Big Data toolset is Hadoop, an open-source batch processing toolkit

* This book will present several (paradigms for/ways to think about) Big Data analytics
* Hadoop serves well as a distributed runner.
* One (approach/paradigm) is record-oriented

Data is worthless. Actually, it's worse than worthless: it requires money and effort to collect, store, transport and organize. Nobody wants data.

What everybody wants is _insight_ -- the patterns, connections, (summarizations) that lead to deeper understanding and better decisions

1. Process records independently into a new form
2. Assemble records into context
3. Synthesize context groups into new forms
4. Write the results to a datastore or external system

* Operations that apply locally to each partition and cause no network transfer
* Repartitioning operations that repartition a stream but otherwise don't change the contents (involves network transfer)
* Aggregation operations that do network transfer as part of the operation
* Operations on grouped streams
* Merges and joins

data flutters by              (process and label records)
elephants make sturdy piles   (contextify? assemble? by label)
context yields insight        (process context groups)

We'll start with an application that only requires processing records independently -- each record requires no context.
You'll learn the mechanics of running Hadoop jobs: how to load and retrieve data, launch your job and see its progress, and so forth.
But Hadoop is useful for far more than such
 so-called "embarrassingly parallel" problems.
The second program exhibits the full map-reduce paradigm.
The program is simple, but it's _scalable_. Slight modification of the program to
Count 56,000 UFO sightings by month
  Build the analogous timeseries for the X billion Wikipedia pages.

We've just seen how
 Now let's understand a high-level picture of
  What Hadoop is doing, and why this makes it scalable.
(Merge sort, secondary sort)

So far we've seen two paradigms: distributed work
Record-oriented

* Letters to toyforms
* Toyforms to parts forms, parts and toyforms to desks
* Toys by type and subtype
* Toys by crate and then address


1. Introduction
2. Hadoop Basics
    * Elephant and Chimpanzee Start a Business
    * Translating Pig Latin with Hadoop
    * Running a Hadoop Job
        * Transfer Data to the Cluster
        * Running and Monitoring your Job
        * Viewing Output
    * How the HDFS Manages Data
3. Map/Reduce Analytics
    * When are UFOs Most Likely to be Seen?
        * Mappers Label Sightings by Hour
        * Hadoop Groups Each Hour's Sightings
        * Reducer Counts the Sightings
    * Elephant and Chimpanzee Save Christmas part 1
        * Elves in Crisis
        * Making Toys: Children's letters Become Labelled Toy Forms
        * Making Toys: Toy Forms Dispatched to Workbench
    * Map/reduce
        * Mapper labels records
        * Hadoop groups records by label
        * Reducer processes each group
        * Default Partitioner Distributes Keys Uniformly
        * Experimenting With Partitions
    * Elephant and Chimpanzee Save Christmas part 2
        * A New Scaling Bottleneck
        * Reindeer Games
        * The New Parts System
    * Secondary Sort
        * Extend UFO Sighting Records with Geographic Info
        * Putting Sightings and Places into Context by Location Name
        * Secondary Sort to Match Records
    * Repeatable Patterns We've Seen: Aggregation, Filter, Co-group
4. Pig Gives Hadoop Full-Dataset Operations
    * Using Pig to Count UFO Sightings
    * Olga the Remarkable Calculating Pig
    * Running Pig Jobs and Monitoring Progress
    * LOAD Sources Your Data and Defines its Schema
    * Pig Operations act on Tables
    * Pig Functions Act on Records
    * STORE Specifies Output Location and Triggers Execution
    * Directives that aid development: DESCRIBE, ASSERT, LIMIT..DUMP, ILLUSTRATE, EXPLAIN
        * DESCRIBE shows the schema of a table
        * ASSERT checks that your data is as you think it is
        * LIMIT..DUMP shows data on the console
        * ILLUSTRATE magically simulates your script’s actions, except when it fails to work
        * EXPLAIN shows Pig’s execution graph
5. Fundamental Patterns of Map/Reduce Analytics
    * Overview of Operations
    * FOREACH processes records individually
    * FILTER
    * LIMIT
    * JOIN matches records in two tables
    * Use a Replicated JOIN When One Table is Small
    * GROUP with Aggregating Functions for Summarizing
    * GROUP or COGROUP to Reassemble Records
    * After a GROUP, a FOREACH has special abilities
    * FLATTEN Ungroups records
6. Big Data Ecosystem
    * Batch Processing
        * Sidebar: Which Hadoop Version?
    * Streaming Data Processing
    * Stream Analytics
    * Online Analytic Processing (OLAP)
    * Core Platform: Data Stores
        * Traditional Relational Databases
        * Billion-Record Datastores
        * Scalable Application-Oriented Datastores
        * Scalable Free-Text Search Engines
        * Other Datastores
* Programming Languages, Tools and Frameworks

Frameworks

7. Cat Herding
8. .
9. ...
10. ...
11. ...
12. Hadoop Internals
    * What's Fast at Scale



==== Our Questions for You ====

* The rule of thumb I'm using on introductory material is "If it's well-covered on the internet, leave it out". It's annoying when tech books give a topic the bus-tour-of-London ("On your window to the left is the outside of the British Museum!") treatment, but you should never find yourself completely stranded. Please let me know if that's the case.
* Analogies: We'll be accompanied on part of our journey by Chimpanzee and Elephant, whose adventures are surprisingly relevant to understanding the internals of Hadoop. I don't want to waste your time laboriously remapping those adventures back to the problem at hand, but I definitely don't want to get too cute with the analogy. Again, please let me know if I err on either side.


==== What's Covered in This Book? ====

1. *First Exploration*:

Objective: Show you a thing you couldn’t do without hadoop, you couldn’t do it any other way. Your mind should be blown and when you’re slogging through the data munging chapter you should think back to this and remember why you started this mess in the first place.

A walkthrough of problem you'd use Hadoop to solve, showing the workflow and thought process. Hadoop asks you to write code poems that compose what we'll call _transforms_ (process records independently) and _pivots_ (restructure data).

2. *Hadoop Processes Billions of Records*

Chimpanzee and Elephant are hired to translate the works of Shakespeare to every language; you'll take over the task of translating text to Pig Latin. This is an "embarrassingly parallel" problem, so we can learn the mechanics of launching a job and a coarse understanding of the HDFS without having to think too hard.

* Chimpanzee and Elephant start a business
* Pig Latin translation
* Test job on commandline
* Load data onto HDFS
* Run job on cluster
* See progress on jobtracker, results on HDFS
* Message Passing -- visit frequency
* SQL-like Set Operations -- visit frequency II
* Graph operations
  
3. *Hadoop Derives Insight from Data in Context* -- You've already seen the first trick: processing records individually. The second trick is to form sorted context groups. There isn't a third trick. With these tiny two mustard seeds -- process and contextify -- we can reconstruct the full set of data analytic operations that turn mountains of data into gems of insight. C&E help SantaCorp optimize the Christmas toymaking process, demonstrating the essential problem of data locality (the central challenge of Big Data). We'll follow along with a job requiring map and reduce, and learn a bit more about Wukong (a Ruby-language framework for Hadoop).

* Chimpanzee and elephant sve Christmas pt 1
* map/reduce: count ufo sightings
* The Hadoop Haiku
* Hadoop vs Traditional databases
* Chimpanzee and elephant sve Christmas pt 2
* reducer guarantee
* reducers in action
* secondary sort

4. *Hadoop Enables SQL-like Set Operations*

By this point in the book  you should: a) Have your mind blown; b) See some compelling enough data and a compelling enough question, and a wukong job that answers that job by using only a mapper; c) see some compelling enough data and a compelling enough question, which requires a map and reduce job, written in both pig and wukong; d) believe the mapreduce story, i.e. you know, in general, the high-level conceptual mechanics of a mapreduce job. You'll have seen whimsical & concrete explanations of mapreduce,  what’s happening as a job is born and run, and HDFS

* Count UFO visits by month
  - visit jobtracker to see what Pig is doing
* Counting Wikipedia pageviews by hour (or whatever)
  - should be same as UFO exploration, but: will actually require Hadoop also do a total sort at the end

4. *Fundamental Data Operations in Hadoop*

Here’s the stuff you’d like to be able to do with data, in wukong and in pig

* Foreach/filter operations (messing around inside a record)
* reading data (brief practical directions on the level of “this is what you type in”)
* limit
* filter
* sample
* using a hash digest function to take a signature
* top k and reservoir sampling
* refer to subuniverse which is probably elsewhere
* group
* join
* ??cogroup?? (does this go with group? Does it go anywhere?)
* sort, etc.. : cross cube
* total sort
* partitioner
* basic UDFs
* ?using ruby or python within a pig dataflow?

5. *Analytic Patterns*

Connect the structural operations you've seen pig do with what is happeining underneath, and flesh out your understanding of them.

6. *The Hadoop Toolset and Other Practical Matters*

* toolset overview
* It’s a necessarily polyglot sport
* Pig is a language that excels at describing
* we think you are doing it wrong if you are not using :
* a declarative orchestration language, a high-level scripting language for the dirty stuff (e.g. parsing, contacting external apis, etc..)
*  udfs (without saying udfs) are for accessing a java-native library, e.g. geospacial libraries, when you really care about performance, to gift pig with a new ability, custom loaders, etc…
* there are a lot of tools, they all have merits: Hive, Pig, Cascading, Scalding, Wukong, MrJob, R, Julia (with your eyes open), Crunch. There aren’t others that we would recommend for production use, although we see enough momentum from impala and spark that you can adopt them with confidence that they will mature.
* launching and debugging jobs
* overview of Wukong
* overview of Pig

7. *Filesystem Mojo and `cat` herding*

* dumping, listing, moving and manipulating files on the HDFS and local filesystems
* total sort
* transformations from the commandline (grep, cut, wc, etc)
* pivots from the commandline (head, sort, etc)
* commandline workflow tips
* advanced hadoop filesystem (chmod, setrep, fsck)

* pig schema
* wukong model
* loading TSV
* loading generic JSON
* storing JSON
* loading schematized JSON
* loading parquet or Trevni
* (Reference the section on working with compressed files; call back to the points about splitability and performance/size tradeoffs)
* TSV, JSON, not XML; Protobufs, Thrift, Avro; Trevni, Parquet; Sequence Files; HAR
* compression: gz, bz2, snappy, LZO
* subsetting your data
  
8. *Intro to Storm+Trident*

* Meet Nim Seadragon
* What and Why Storm and Trident
* First Storm Job

9. *Statistics*:

* (this is first deep experience with Storm+Trident)
* Summarizing: Averages, Percentiles, and Normalization
* running / windowed stream summaries
  - make a "SummarizingTap" trident operation that collects {Sum Count Min Max Avg Stddev SomeExampleValuesReservoirSampled} (fill in the details of what exactly this means)
  - also, maybe: Median+Deciles, Histogram
  - understand the flow of data going on in preparing such an aggregate, by either making sure the mechanics of working with Trident don't overwhelm that or by retracing the story of records in an aggregation
  - you need a group operation -> means everything in group goes to exactly one executor, exactly one machine, aggregator hits everything in a group
* combiner-aggregators (in particular), do some aggregation beforehand, and send an intermediate aggregation to the executor that hosts the group operation
  - by default, always use persistent aggregate until we find out why you wouldn’t
  - (BUBBLE) highlight the corresponding map/reduce dataflow and illuminate the connection
* (BUBBLE) Median / calculation of quantiles at large enough scale that doing so is hard
* (in next chapter we can do histogram)
* Use a sketching algorithm to get an approximate but distributed answer to a holistic aggregation problem eg most frequent elements
* Rolling timeseries averages
* Sampling responsibly: it's harder and more important than you think
  - consistent sampling using hashing
  - don’t use an RNG
  - appreciate that external data sources may have changed
  - reservoir sampling
  - connectivity sampling (BUBBLE)
  - subuniverse sampling (LOC?)
* Statistical aggregates and the danger of large numbers
  - numerical stability
  - overflow/underflow
  - working with distributions at scale
  - your intuition is often incomplete
  - with trillions of things, 1 in billion chance things happen thousands of times
* weather temperature histogram in streaming fashion
* approximate distinct counts (using HyperLogLog)
* approximate percentiles (based on quantile digest)

10. *Time Series and Event Log Processing*:

* Parsing logs and using regular expressions with Hadoop
  - logline model
  - regexp to match lines, highlighting this as a parser pattern
  - reinforce the source blob -> source model -> domain model practice
* Histograms and time series of pageviews using Hadoop
* sessionizing
  - flow chart throughout site?
  - "n-views": pages viewed in sequence
  - ?? Audience metrics:
  - make sure that this serves the later chapter with the live recommender engine (lambda architecture)
* Geolocate visitors based on IP with Hadoop
  - use World Cup data?
  - demonstrate using lookup table,
  - explain it as a range query
  - use a mapper-only (replicated) join -- explain why using that (small with big) but don't explain what it's doing (will be covered later)
* (Ab)Using Hadoop to stress-test your web server

Exercise: what predicts the team a country will root for next? In particular: if say Mexico knocks out Greece, do Greeks root for, or against, Mexico in general?

11. *Geographic Data*:

* Spatial join (find all UFO sightings near Airports) of points with points
  - map points to grid cell in the mapper; truncate at a certain zoom level (explain how to choose zoom level). must send points to reducers for own grid key and also neighbors (9 total squares).
  - Perhaps, be clever about not having to use all 9 quad grid neighbors by partitioning on a grid size more fine-grained than your original one and then use that to send points only the pertinent grid cell reducers
  - Perhaps generate the four points that are x away from you and use their quad cells.
* In the reducer, do point-by-point comparisons
  - *Maybe* a secondary sort???
* Geospacial data model, i.e. the terms and fields that you use in, e.g. GeoJSON
  - We choose X, we want the focus to be on data science not on GIS
  - Still have to explain ‘feature’, ‘region’, ‘latitude’, ‘longitude’, etc…
* Decomposing a map into quad-cell mapping at constant zoom level
  - mapper input: `<name of region, GeoJSON region boundary>`; Goal 1: have a mapping from region -> quad cells it covers; Goal 2: have a mapping from quad key to partial GeoJSON objects on it. mapper output: [thing, quadkey] ; [quadkey, list of region ids, hash of region ids to GeoJSON region boundaries]
* Spatial join of points with regions, e.g. what congressional district are you in?
  - in mapper for points emit truncated quad key, the rest of the quad key, just stream the regions through (with result from prior exploration); a reducer has quadcell, all points that lie within that quadcell, and all regions (truncated) that lie on that quadcell. Do a brute force search for the regions that the points lie on
* Nearness query
  - suppose the set of items you want to find nearness to is not huge; produce the voronoi diagrams
* Decomposing a map into quad-cell mapping at multiple zoom levels;in particular, use voronoi regions to make show multi-scale decomposition
* Re-do spatial join with Voronoi cells in multi-scale fashion (fill in details later)
  - Framing the problem (NYC vs Pacific Ocean)
  - Discuss how, given a global set of features, to decompose into a multi-scale grid representation
  - Other mechanics of working with geo data

12. *Conceptual Model for Data Analysis*

* There's just one framework

13. *Data Munging (Semi-Structured Data)*: The dirty art of data munging. It's a sad fact, but too often the bulk of time spent on a data exploration is just getting the data ready. We'll show you street-fighting tactics that lessen the time and pain. Along the way, we'll prepare the datasets to be used throughout the book:

* Datasets
  - Wikipedia Articles: Every English-language article (12 million) from Wikipedia.
  - Wikipedia Pageviews: Hour-by-hour counts of pageviews for every Wikipedia article since 2007.
  - US Commercial Airline Flights: every commercial airline flight since 1987
  - Hourly Weather Data: a century of weather reports, with hourly global coverage since the 1950s.
  - "Star Wars Kid" weblogs: large collection of apache webserver logs from a popular internet site (Andy Baio's waxy.org).
* Wiki pageviews - String encoding and other bullshit
* Airport data -Reconciling to *mostly* agreeing datasets
* Something that has errors (SW Kid) - dealing with bad records
* Weather Data - Parsing a flat pack file
  - bear witness, explain that you DID have to temporarily become an ameteur meteorologist, and had to write code to work with that many fields.
  - when your schema is so complicated, it needs to be automated, too.
  - join hell, when your keys change over time
* Data formats
  - airing of grievances on XML
  - airing of grievances on CSV
  - don’t quote, escape
  - the only 3 formats you should use, and when to use them
* Just do a data munging project from beginning to end that wasn’t too horrible
  - Talk about the specific strategies and tactics
  - source blob to source domain object, source domain object to business object. e.g. you want your initial extraction into a model mirrors closely the source domain data format. Mainly because you do not want mix your extraction logic and business logic (extraction logic will pollute business objects code). Also, will end up building the wrong model for the business object, i.e. it will look like the source domain.
* Airport data - chief challenge is reconciling data sets, dealing with conflicting errors

13. *Machine Learning without Grad School*: We'll equip you with a picture of how they work, but won't go into the math of how or why. We will show you how to choose a method, and how to cheat to win. We'll combine the record of every commercial flight since 1987 with the hour-by-hour weather data to predict flight delays using
  
* Naive Bayes
* Logistic Regression
* Random Forest (using Mahout)

14. *Full Application: Regional Flavor*

15. *Hadoop Native Java API*

* don't

19. *Advanced Pig*

* Specialized joins that can dramatically speed up (or make feasible) your data transformations
* why algebraic UDFs are awesome and how to be algebraic
* Custom Loaders
* Performance efficiency and tunables
* using a filter after a cogroup will get pushed up by Pig, sez Jacob

20. *Data Modeling for HBase-style Database*

21. *Hadoop Internals*

* What happens when a job is launched
* A shallow dive into the HDFS

=====  HDFS

Lifecycle of a File:

* What happens as the Namenode and Datanode collaborate to create a new file.
* How that file is replicated to acknowledged by other Datanodes.
* What happens when a Datanode goes down or the cluster is rebalanced.
* Briefly, the S3 DFS facade // (TODO: check if HFS?).

===== Hadoop Job Execution

* Lifecycle of a job at the client level including figuring out where all the source data is; figuring out how to split it; sending the code to the JobTracker, then tracking it to completion.
* How the JobTracker and TaskTracker cooperate to run your job, including:  The distinction between Job, Task and Attempt., how each TaskTracker obtains its Attempts, and dispatches progress and metrics back to the JobTracker, how Attempts are scheduled, including what happens when an Attempt fails and speculative execution, ________, Split.
* How TaskTracker child and Datanode cooperate to execute an Attempt, including; what a child process is, making clear the distinction between TaskTracker and child process.
* Briefly, how the Hadoop Streaming child process works.

==== Skeleton: Map-Reduce Internals

* How the mapper and Datanode handle record splitting and how and when the partial records are dispatched.
* The mapper sort buffer and spilling to disk (maybe here or maybe later, the I/O.record.percent).
* Briefly note that data is not sent from mapper-to-reducer using HDFS and so you should pay attention to where you put the Map-Reduce scratch space and how stupid it is about handling an overflow volume.
* Briefly that combiners are a thing.
* Briefly how records are partitioned to reducers and that custom partitioners are a thing.
* How the Reducer accepts and tracks its mapper outputs.
* Details of the merge/sort (shuffle and sort), including the relevant buffers and flush policies and why it can skip the last merge phase.
* (NOTE:  Secondary sort and so forth will have been described earlier.)
* Delivery of output data to the HDFS and commit whether from mapper or reducer.
* Highlight the fragmentation problem with map-only jobs.
* Where memory is used, in particular, mapper-sort buffers, both kinds of reducer-merge buffers, application internal buffers.

18. *Hadoop Tuning*
  - Tuning for the Wise and Lazy
  - Tuning for the Brave and Foolish
  - The USE Method for understanding performance and diagnosing problems

19. *Storm+Trident Internals*

* Understand the lifecycle of a Storm tuple, including spout, tupletree and acking.
* (Optional but not essential) Understand the details of its reliability mechanism and how tuples are acked.
* Understand the lifecycle of partitions within a Trident batch and thus, the context behind partition operations such as Apply or PartitionPersist.
* Understand Trident’s transactional mechanism, in the case of a PartitionPersist.
* Understand how Aggregators, Statemap and the Persistence methods combine to give you _exactly once_  processing with transactional guarantees.  Specifically, what an OpaqueValue record will look like in the database and why.
* Understand how the master batch coordinator and spout coordinator for the Kafka spout in particular work together to uniquely and efficiently process all records in a Kafka topic.
* One specific:  how Kafka partitions relate to Trident partitions.

20. *Storm+Trident Tuning*

23. *Overview of Datasets and Scripts*
 - Datasets
   - Wikipedia (corpus, pagelinks, pageviews, dbpedia, geolocations)
   - Airline Flights
   - UFO Sightings
   - Global Hourly Weather
   - Waxy.org "Star Wars Kid" Weblogs
 - Scripts

24. *Cheatsheets*:
  - Regular Expressions
  - Sizes of the Universe
  - Hadoop Tuning & Configuration Variables


Chopping block

1. Interlude I: *Organizing Data*:
  - How to design your data models
  - How to serialize their contents (orig, scratch, prod)
  - How to organize your scripts and your data

2. *Graph Processing*:
  - Graph Representations
  - Community Extraction: Use the page-to-page links in Wikipedia to identify similar documents
  - Pagerank (centrality): Reconstruct pageview paths from web logs, and use them to identify important pages

3. *Text Processing*: We'll show how to combine powerful existing libraries with hadoop to do effective text handling and Natural Language Processing:
  - Indexing documents
  - Tokenizing documents using Lucene
  - Pointwise Mutual Information
  - K-means Clustering

4. Interlude II: *Best Practices and Pedantic Points of style*
  - Pedantic Points of Style
  - Best Practices
  - How to Think: there are several design patterns for how to pivot your data, like Message Passing (objects send records to meet together); Set Operations (group, distinct, union, etc); Graph Operations (breadth-first search). Taken as a whole, they're equivalent; with some experience under your belt it's worth learning how to fluidly shift among these different models.
  - Why Hadoop
  - robots are cheap, people are important


17. Interlude II: *Best Practices and Pedantic Points of style*
  - Pedantic Points of Style
  - Best Practices
  - How to Think: there are several design patterns for how to pivot your data, like Message Passing (objects send records to meet together); Set Operations (group, distinct, union, etc); Graph Operations (breadth-first search). Taken as a whole, they're equivalent; with some experience under your belt it's worth learning how to fluidly shift among these different models.
  - Why Hadoop
  - robots are cheap, people are important

14. Interlude I: *Organizing Data*:
  - How to design your data models
  - How to serialize their contents (orig, scratch, prod)
  - How to organize your scripts and your data


