[[analytic_patterns]]
= Part 2: Analytic Patterns

Now that you've met the fundamental analytic machinery -- in both their map/reduce and table-operation form -- it's time to put them to work.

This part of the book will equip you to think tactically, to think in terms of the changes you would like to make to the data. Each section introduces a repeatedly-useful data transformation pattern, demonstrated in Pig (and, where we'd like to reinforce the record-by-record action, in Wukong as well). The next part of the book will focus on _strategic_ techniques, to assemble the patterns you're about to see into an explanation that tells a coherent story.

One of this book's principles is to center demonstrations around an interesting and realistic problem from some domain. And whenever possible, we endeavor to indicate how the approach would extend to other domains, especially ones with an obvious business focus. The tactical patterns, however, are exactly those tools that crop up in nearly every domain: think of them as the screwdriver, torque wrench, lathe and so forth of your toolkit. Now, if this book were called "Big Mechanics for Chimps", we might introduce those tools by repairing and rebuilding a Volkswagen Beetle engine, or by building another lathe from scratch. Those lessons would carry over to anywhere machine tools apply: air conditioner repair, fixing your kid's bike, building a rocket ship to Mars.

To meet our standard of interesting and realistic demonstrations, we need some domain to explore. And to keep focus on the patterns and not on specifics of the data model or domain, it's best to choose one and stick with it. So we will center these next few chapters on what Nate Silver calls "the perfect data set": the sea of numbers surrounding the sport of baseball. The members of the Retrosheet and Baseball Databank projects have provided an extraordinary resource: comprehensive statistics from the birth of the game in the late 1800s until the present day, freely available and redistributable. There is an overview of the stats we'll use in (REF sidebar), and further information in the "Overview of Datasets" appendix (REF). Even if you're not a baseball fan, we've minimized the number of concepts you'll need to learn.

This means, however, that you may find yourself looking at a pattern and saying "geez, I don't see how this would apply to my work in \[quantitative finance|manufacturing|basketweaving|etc\]". It might be the case that it doesn't apply; a practicing air conditioner repair person has generally not much use for a lathe. In many other cases it does apply, but you won't see how until some late night when your back's against the wall and you remember that one section in that covered "Splitting a Table into Uniform Chunks" and an hour later you tweet "No doubt about it, I sure am glad I purchased 'Big Data for Chimps'". Our belief and our goal is that it's most commonly the second scenario.

The sections on "pattern in use" will become most useful once you've read the book a first time and (we hope) begin using it as your go-to reference. If you find the level of detail here to be a bit intense, skim past them on the first reading. footnote:[The authors' universal experience is that when we do come back, we read past at least problem that we wasted two days figuring out on our own... But of course it was only by figuring out that problem that the other things became intelligible anyway.]
