[[glossary]]
== Glossary ==

* secondarynn (aka "secondary namenode") -- handles compaction of namenode directory. It is NOT a backup for the namenode.
* support daemon			 -- one of namenode, datanode, jobtracker, tasktracker or secondarynn.
* job process (aka "child process")	 -- the actual process that executes your code
* tasktracker				 -- interface between jobracker and task processes. It does NOT execute your code, and typically requires a minimal amount of RAM.
* shuffle merge				 -- (aka shuffle and sort)
* shuffle buffer			 -- 
* map sort buffer			 -- 
* Resident memory (RSS or RES)		 -- 
* JVM					 -- 
* JVM heap size				 -- 
* Old-Gen heap				 -- 
* New-Gen heap				 -- portion of JVM ram used for short-lived objects. If too small, transient objects will go into the old-gen, causing fragmentation and an eventual STW garbage collection.
* garbage collection			 -- 
* STW garbage collection		 -- "Stop-the-world" garbage collection, a signal that there has been significant fragmentation or heap pressure. Not Good.
* attempt ID				 -- 
* task ID				 -- 
* job ID				 -- 

Questions:

* "task process" or "job process" for child process?

=== Storm+Trident Glossary ===

Storm Execution

* Worker
* Daemons
  - Nimbus
  - UI
  - Supervisor
  - Child Process
* Executor
* Task
* Trident Function

Trident

* Tuple / TridentTuple
* tupletree
* Batch
* Partition
* Group
* Batch (Transaction) ID
* TridentOperation
* TridentFunction
* Aggregator
*

Layout

* Topology
* Stream
* Assembly
*

Internal

* Master Batch Coordinator
* Spout Coordinator
* TridentSpoutExecutor
* TridentBoltExecutor

Transport

* DisruptorQueue
* Executor Send Queu
* Executor Receive Queue
* Worker Transfer Queue
* (Worker Receive Buffer)
