== End Material ==

=== Author ===

Philip (flip) Kromer is cofounder of Infochimps, a big data platform that makes acquiring, storing and analyzing massive data streams transformatively easier.  Infochimps became part of Computer Sciences Corporation in 2013, and their big data platform now serves customers such as Cisco, HGST and Infomart. He enjoys Bowling, Scrabble, working on old cars or new wood, and rooting for the Red Sox. 

Graduate School, Dept. of Physics - University of Texas at Austin, 2001-2007
Bachelor of Arts, Computer Science - Cornell University, Ithaca NY, 1992-1996

* Cofounder of Infochimps, now Head of Technology and Architecture at Infochimps, a CSC Company.
* Core committer for Storm, a framework for scalable stream processing and analytics
* Core committer for Ironfan, a framework for provisioning complex distributed systems in the cloud or data center
* Original author and core committer of Wukong, the leading Ruby library for Hadoop
* Contributed chapter to _The Definitive Guide to Hadoop_ by Tom White

TODO Russell: biography

=== Colophon ===

Writing a book with O'Reilly is magic in so many ways, but none moreso than their Atlas authoring platform. Rather than the XML hellscape that most publishers require, Atlas allows us to write simple text documents with readable markup, do a `git push`, and see a holy-smokes-that-looks-like-a-real-book PDF file moments later. 

* Emacs, because a text editor that isn't its own operating system might as well be edlin.
* Visuwords.com give good word when brain not able think word good. 
* Posse East Bar and Epoch Coffee House in Austin provided us just the right amount of noise and focus for cranking out content.
* http://dexy.it is a visionary tool for writing documentation. With it, we are able to directly use the runnable example scripts as the code samples for the book.

=== Back Cover

==== Short description

Working with big data for the first time? This unique guide shows you how to use simple, fun, and elegant tools working with Apache Hadoop. You’ll learn how to break problems into efficient data transformations to meet most of your analysis needs. It’s an approach that not only works well for programmers just beginning to tackle big data, but for anyone using Hadoop.

==== Long description

This unique guide shows you how to use simple, fun, and elegant tools leveraging Apache Hadoop to answer big data questions. You’ll learn how to break problems into efficient data transformations to meet most of your analysis needs. Its developer-friendly approach works well for anyone using Hadoop, and flattens the learning curve for those working with big data for the first time.

Written by Philip Kromer, founder and CTO at Infochimps, this book uses real data and real problems to illustrate patterns found across knowledge domains. It equips you with a fundamental toolkit for performing statistical summaries, text mining, spatial and time-series analysis, and light machine learning. For those working in an elastic cloud environment, you'll learn superpowers that make exploratory analytics especially efficient.

* Learn from detailed example programs that apply Hadoop to interesting problems in context
* Gain advice and best practices for efficient software development
* Discover how to think at scale by understanding how data must flow through the cluster to effect transformations
* Identify the tuning knobs that matter, and rules-of-thumb to know when they're needed.
Learn how and when to tune your cluster to the job and 
