=== Other Datasets ===


    approx size	Mrecs	source Data
           huge		US Patent Data from Google                          	www.google.com/googlebooks/uspto-patents.html[Google Patent Collection]
           huge	      1	Mathematical constants to billion+ digits         	www.numberworld.org/ftp
     2_300_000	 250000	Wikipedia Pageview Stats                           	dumps.wikimedia.org/other/pagecounts-raw
       470_000	      	Wikibench.eu Wikipedia Log traces                   	Wikibench.eu
       124_000	1300000	Access Logs, 1998 World Cup (Internet Traffic Archive)	access_logs/ita/ita_world_cup
        40_000	 B	NCDC: Hourly Weather (full)                         	ftp.ncdc.noaa.gov/pub/data/noaa
        34_000	     10	MLB Gameday Pitch-by-pitch data, 2007-2011          	gd2.mlb.com/components/game/mlb
        16_000	    619	Wikipedia corpus and pagelinks                      	dumps.wikimedia.org/enwiki/20120601
        14_000	  	NCDC: Hourly weather (simplified)                   	ftp.ncdc.noaa.gov/pub/data/noaa/isd-lite
        14_000		Memetracker                                         	snap.stanford.edu/data/bigdata/memetracker9
        14_000		Amazon Co-Purchasing Data                           	snap.stanford.edu/data/bigdata/amazon0312.html
        11_000		Crosswikis                                          	nlp.stanford.edu/pubs/crosswikis-data.tar.bz2
         6_400		NCDC: Daily Weather                                 	ftp.ncdc.noaa.gov/pub/data/gsod
         6_300		Berkeley Earth Surface Temperature                  	stats/earth_surface_temperature
         2_900		Twilio TigerLINE US Street Map                      	geo/us_street_map/addresses
         1_900		All US Airline Flights 1987-2009 (ASA Data Expo)    	stat-computing.org/dataexpo/2009
         1_300		Geonames Points of Interest                         	geo/geonames/info
         1_300		Daily Prices for all US stocks, 1962–2011           	stats/stock_prices
         1_040		Patent data (see Google data too)                   	www.nber.org/~jbessen
           573		TAKS Exam Scores for all Texas students, 2007-2010  	ripd/texas_taks_exam
           571		Pi to 1 Billion decimal places                      	ja0hxv.calico.jp/value/pai/val01/pi
           419		Enron Email Corpus                                  	lang/corpora/enron_trial_coporate_email_corpus
           362		DBpedia Wikipedia Article Features                  	downloads.dbpedia.org/3.7/links
           331		DBpedia                                             	spotlight.dbpedia.org/datasets
           310		Grouplens: User-Movie affinity                       	graph/grouplens_movies
           305		UFO Sightings (UFORC)                               	geo/ufo_sightings
           223		Geonames Postal Codes                               	geo/geonames/postal_codes
           121		Book Crossing: User-Book affinity                   	graph/book_crossing
           111		Maxmind GeoLite (IP-Geo) data                       	ripd/geolite.maxmind.com/download
            91		Access Logs: waxy.org's Star Wars Kid logs          	access_logs/star_wars_kid
            62		Metafilter corpus of postings with metadata         	ripd/stuff.metafilter.com/infodump
            47		Word frequencies from the British National Corpus   	ucrel.lancs.ac.uk/bncfreq/lists
            36		Mobywords thesaurus                                 	lang/corpora/thesaurus_mobywords
            25		Retrosheet: MLB play-by-play, high detail, 1840-2011	ripd/www.retrosheet.org-2007/boxesetc/2006
            25		Retrosheet: MLB box scores, 1871-2011               	ripd/www.retrosheet.org-2007/boxesetc/2006
            20		US Federal Reserve Bank Loans (Bloomberg)           	misc/bank_loans_by_fed
            11		Scrabble dictionaries                               	lang/corpora/scrabble
            11		All Scrabble tile combinations with rack value      	misc/words_quackle
              .	       	Marvel Universe Social Graph
              .		Materials Safety Datasheets
              .		Crunchbase
              .		Natural Earth detailed geographic boundaries
              .		US Census 2009 ACS (Long-form census)
              .		US Census Geographic boundaries
              .		Zillow US Neighborhood Boundaries
              .		Open Street Map
      2_000_000		Google Books N-Grams                                	aws.amazon.com/datasets/8172056142375670
     60_000_000		Common Crawl Web Corpus
        600_000		Apache Software Foundation Public Mail Archives 	aws.amazon.com/datasets/7791434387204566
        300_000		Million-Song dataset                              	labrosa.ee.columbia.edu/millionsong/ This corpus is a collection of public USENET postings. This corpus was collected between Oct 2005 and Jan 2011, and covers 47860 English language, non-binary-file news groups. Despite our best effots, this corpus includes a very small number of non-English words, non-words, and spelling errors. The corpus is untagged, raw text. It may be neccessary to process the corpus further to put the corpus in a format that suits your needs.
             		Reference Energy Disaggregation Dataset (REDD)   	redd.csail.mit.edu/
                         US Legislation Co-Sponsorship                     	jhfowler.ucsd.edu/cosponsorship.htm
                         VoteView: Political Spectrum Rank of US Legistors/Laws	voteview.org/downloads.asp	DW-NOMINATE Rank Orderings all Houses and Senates
         		World Bank                                       	data.worldbank.org
                         Record of American Democracy                      	road.hmdc.harvard.edu/pages/road-documentation     	The Record Of American Democracy (ROAD) data includes election returns, socioeconomic summaries, and demographic measures of the American public at unusually low levels of geographic aggregation. The NSF-supported ROAD project covers every state in the country from 1984 through 1990 (including some off-year elections). One collection of data sets includes every election at and above State House, along with party registration and other variables, in each state for the roughly 170,000 precincts nationwide (about 60 times the number of counties). Another collection has added to these (roughly 30-40) political variables an additional 3,725 variables merged from the 1990 U.S. Census for 47,327 aggregate units (about 15 times the number of counties) about the size one or more cities or towns. These units completely tile the U.S. landmass. The collection also includes geographic boundary files so users can easily draw maps with these data.
           		Human Mortality DB                                	www.mortality.org/                                  	The Human Mortality Database (HMD) was created to provide detailed mortality and population data to researchers, students, journalists, policy analysts, and others interested in the history of human longevity. The project began as an outgrowth of earlier projects in the Department of Demography at the University of California, Berkeley, USA, and at the Max Planck Institute for Demographic Research in Rostock, Germany (see history). It is the work of two teams of researchers in the USA and Germany (see research teams), with the help of financial backers and scientific collaborators from around the world (see acknowledgements).
           		FCC Antenna locations                                	transition.fcc.gov/mb/databases/cdbs
           		Pew Research Datasets                                	pewinternet.org/Static-Pages/Data-Tools/Download-Data/Data-Sets.aspx
           		Youtube Related Videos                                	netsg.cs.sfu.ca/youtubedata
              .		Westbury Usenet Archive                              	www.psych.ualberta.ca/~westburylab/downloads/usenetcorpus.download.html	 USENET corpus (2005-2010)

