container:
	docker build -t pmoust/squid-deb-proxy .

# ( cd $DF_DIR; docker stop deb-proxy ; docker build -t $ctr ./$ctr && docker rm $ctr && docker run --name $ctr --rm -v /tmp/deb-proxy:/deb-proxy -p 8000:8000 $ctr )
deb-proxy
