--
-- Help taken from [Hardball Times]http://www.hardballtimes.com/tht-live/building-a-retrosheet-database-the-short-form/
-- and [Baseball Hacks](http://examples.oreilly.com/9780596009427/)
--
-- Fields described in http://www.retrosheet.org/gamelogs/glfields.txt
--

-- (cat game_log_headers.csv ;  cat raw/game_logs/GL*.TXT | ruby -ne 'puts $_.gsub(/,(?=,)/, ",\\N")' ) > raw/game_logs-1871-2013.csv

USE `retrosheet`;

--
-- Notes:
--
-- some field names modified to match baseball_databank ones: year_id vs year__id, etc.
-- note that players are identified with "retro_id" in the people table, not player_id
--

DROP TABLE IF EXISTS `games`;
CREATE TABLE         `games` (
  game_id            CHAR(12)          DEFAULT NULL,
  year_id            INT(4)            NOT NULL DEFAULT '0',
  game_date          DATE              NOT NULL,
  game_start_time    TIME              NOT NULL DEFAULT "00:00:00",
  --
  game_dt            CHAR(8)           NOT NULL,
  game_ct            TINYINT(1)        DEFAULT NULL,
  game_day_of_week   VARCHAR(9)        DEFAULT NULL,
  away_team_id       CHAR(3)           NOT NULL,
  away_lg_id         CHAR(3)           NOT NULL,
  away_game_seq      INT(3) UNSIGNED   NOT NULL,
  home_team_id       CHAR(3)           NOT NULL,
  home_lg_id         CHAR(3)           NOT NULL,
  home_game_seq      INT(3) UNSIGNED   NOT NULL,
  --
  away_runs_ct       INT(3) SIGNED     DEFAULT NULL,  -- 10
  home_runs_ct       INT(3) SIGNED     DEFAULT NULL,
  tot_outs_ct        INT(3) SIGNED     DEFAULT NULL,
  game_daynight      CHAR(1)           DEFAULT NULL,
  completion_info    VARCHAR(50)       DEFAULT NULL,
  forfeit_info       VARCHAR(50)       DEFAULT NULL,
  protest_info       VARCHAR(50)       DEFAULT NULL,
  park_id            CHAR(5)           DEFAULT NULL,
  park_attendence    INT(7) SIGNED     DEFAULT NULL,
  game_minutes_ct    INT(3) SIGNED     DEFAULT NULL,
  away_linescore     VARCHAR(100)      DEFAULT NULL, -- 20
  home_linescore     VARCHAR(100)      DEFAULT NULL,
  --
  away_AB            INT(3) SIGNED     DEFAULT NULL,
  away_H             INT(3) SIGNED     DEFAULT NULL,
  away_D             INT(3) SIGNED     DEFAULT NULL,
  away_T             INT(3) SIGNED     DEFAULT NULL,
  away_HR            INT(3) SIGNED     DEFAULT NULL,
  away_RBI           INT(3) SIGNED     DEFAULT NULL,
  away_SH            INT(3) SIGNED     DEFAULT NULL,
  away_SF            INT(3) SIGNED     DEFAULT NULL,
  away_HBP           INT(3) SIGNED     DEFAULT NULL,  -- 30
  away_BB            INT(3) SIGNED     DEFAULT NULL,
  away_IBB           INT(3) SIGNED     DEFAULT NULL,
  away_K             INT(3) SIGNED     DEFAULT NULL,
  away_SB            INT(3) SIGNED     DEFAULT NULL,
  away_CS            INT(3) SIGNED     DEFAULT NULL,
  away_GDP           INT(3) SIGNED     DEFAULT NULL,
  away_CI            INT(3) SIGNED     DEFAULT NULL,
  away_LOB           INT(3) SIGNED     DEFAULT NULL,
  away_pit_ids       VARCHAR(255)      DEFAULT NULL,
  away_ER            INT(3) SIGNED     DEFAULT NULL, -- 40
  away_TER           INT(3) SIGNED     DEFAULT NULL,
  away_WP            INT(3) SIGNED     DEFAULT NULL,
  away_balks         INT(3) SIGNED     DEFAULT NULL,
  away_PO            INT(3) SIGNED     DEFAULT NULL,
  away_A             INT(3) SIGNED     DEFAULT NULL,
  away_E             INT(3) SIGNED     DEFAULT NULL,
  away_passed        INT(3) SIGNED     DEFAULT NULL,
  away_DB            INT(3) SIGNED     DEFAULT NULL,
  away_TP            INT(3) SIGNED     DEFAULT NULL,
  --
  home_AB            INT(3) SIGNED     DEFAULT NULL, -- 50
  home_H             INT(3) SIGNED     DEFAULT NULL,
  home_D             INT(3) SIGNED     DEFAULT NULL,
  home_T             INT(3) SIGNED     DEFAULT NULL,
  home_HR            INT(3) SIGNED     DEFAULT NULL,
  home_RBI           INT(3) SIGNED     DEFAULT NULL,
  home_SH            INT(3) SIGNED     DEFAULT NULL,
  home_SF            INT(3) SIGNED     DEFAULT NULL,
  home_HBP           INT(3) SIGNED     DEFAULT NULL,
  home_BB            INT(3) SIGNED     DEFAULT NULL,
  home_IBB           INT(3) SIGNED     DEFAULT NULL, -- 60
  home_K             INT(3) SIGNED     DEFAULT NULL,
  home_SB            INT(3) SIGNED     DEFAULT NULL,
  home_CS            INT(3) SIGNED     DEFAULT NULL,
  home_GDP           INT(3) SIGNED     DEFAULT NULL,
  home_CI            INT(3) SIGNED     DEFAULT NULL,
  home_LOB           INT(3) SIGNED     DEFAULT NULL,
  home_pit_ids       VARCHAR(255)      DEFAULT NULL,
  home_ER            INT(3) SIGNED     DEFAULT NULL,
  home_TER           INT(3) SIGNED     DEFAULT NULL,
  home_WP            INT(3) SIGNED     DEFAULT NULL,
  home_balks         INT(3) SIGNED     DEFAULT NULL, -- 70
  home_PO            INT(3) SIGNED     DEFAULT NULL,
  home_A             INT(3) SIGNED     DEFAULT NULL,
  home_E             INT(3) SIGNED     DEFAULT NULL,
  home_passed        INT(3) SIGNED     DEFAULT NULL,
  home_DB            INT(3) SIGNED     DEFAULT NULL,
  home_TP            INT(3) SIGNED     DEFAULT NULL,
  --
  ump_H_id           CHAR(8)           DEFAULT NULL,
  ump_1B_id          CHAR(8)           DEFAULT NULL,
  ump_2B_id          CHAR(8)           DEFAULT NULL, -- 80
  ump_3B_id          CHAR(8)           DEFAULT NULL,
  ump_LF_id          CHAR(8)           DEFAULT NULL,
  ump_RF_id          CHAR(8)           DEFAULT NULL,
  manager_away_id    CHAR(8)           DEFAULT NULL,
  manager_home_id    CHAR(8)           DEFAULT NULL,
  pit_win_id         CHAR(8)           DEFAULT NULL,
  pit_loss_id        CHAR(8)           DEFAULT NULL,
  pit_save_id        CHAR(8)           DEFAULT NULL,
  bat_gwRBI_id       CHAR(8)           DEFAULT NULL,
  pit_away_start_id  CHAR(8)           DEFAULT NULL, -- 90
  pit_home_start_id  CHAR(8)           DEFAULT NULL,
  --
  bat_away_1__id     CHAR(8)           DEFAULT NULL,
  bat_away_1_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_2__id     CHAR(8)           DEFAULT NULL,
  bat_away_2_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_3__id     CHAR(8)           DEFAULT NULL,
  bat_away_3_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_4__id     CHAR(8)           DEFAULT NULL,
  bat_away_4_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_5__id     CHAR(8)           DEFAULT NULL, -- 100
  bat_away_5_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_6__id     CHAR(8)           DEFAULT NULL,
  bat_away_6_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_7__id     CHAR(8)           DEFAULT NULL,
  bat_away_7_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_8__id     CHAR(8)           DEFAULT NULL,
  bat_away_8_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_away_9__id     CHAR(8)           DEFAULT NULL,
  bat_away_9_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_1__id     CHAR(8)           DEFAULT NULL, -- 110
  bat_home_1_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_2__id     CHAR(8)           DEFAULT NULL,
  bat_home_2_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_3__id     CHAR(8)           DEFAULT NULL,
  bat_home_3_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_4__id     CHAR(8)           DEFAULT NULL,
  bat_home_4_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_5__id     CHAR(8)           DEFAULT NULL,
  bat_home_5_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_6__id     CHAR(8)           DEFAULT NULL, -- 120
  bat_home_6_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_7__id     CHAR(8)           DEFAULT NULL,
  bat_home_7_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_8__id     CHAR(8)           DEFAULT NULL,
  bat_home_8_pos     TINYINT(1) SIGNED DEFAULT NULL,
  bat_home_9__id     CHAR(8)           DEFAULT NULL,
  bat_home_9_pos     TINYINT(1) SIGNED DEFAULT NULL,
  --
  additional_info    VARCHAR(255)      DEFAULT NULL,
  acquisition_info   VARCHAR(100)      DEFAULT NULL, -- 129
  --
  PRIMARY KEY `igame`         (`game_id`,           `year_id`),
  UNIQUE KEY  `iteam_away`    (`away_team_id`,      `year_id`, `game_date`, `game_ct`),
  UNIQUE KEY  `iteam_home`    (`home_team_id`,      `year_id`, `game_date`, `game_ct`),
  KEY         `ipark`         (`park_id`,           `year_id`, `game_date`),
  --
  KEY         `iyear_away`    (`year_id`,           `away_team_id`),
  KEY         `iyear_home`    (`year_id`,           `home_team_id`),
  KEY         `iyear_park`    (`year_id`,           `park_id`),
  KEY         `pit_away`      (`pit_away_start_id`, `year_id`),
  KEY         `pit_home`      (`pit_home_start_id`, `year_id`)
) ENGINE=MyISAM DEFAULT CHARSET=ascii /*!50100 PARTITION BY LIST (YEAR_id) (PARTITION pearly VALUES IN (1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919) ENGINE = MyISAM, PARTITION p1920s VALUES IN (1920,1921,1922,1923,1924,1925,1926,1927,1928,1929) ENGINE = MyISAM, PARTITION p1930s VALUES IN (1930,1931,1932,1933,1934,1935,1936,1937,1938,1939) ENGINE = MyISAM, PARTITION p1940s VALUES IN (1940,1941,1942,1943,1944,1945,1946,1947,1948,1949) ENGINE = MyISAM, PARTITION p1950s VALUES IN (1950,1951,1952,1953,1954,1955,1956,1957,1958,1959) ENGINE = MyISAM, PARTITION p1960s VALUES IN (1960,1961,1962,1963,1964,1965,1966,1967,1968,1969) ENGINE = MyISAM, PARTITION p1970s VALUES IN (1970,1971,1972,1973,1974,1975,1976,1977,1978,1979) ENGINE = MyISAM, PARTITION p1980s VALUES IN (1980,1981,1982,1983,1984,1985,1986,1987,1988,1989) ENGINE = MyISAM, PARTITION p1990s VALUES IN (1990,1991,1992,1993,1994,1995,1996,1997,1998,1999) ENGINE = MyISAM, PARTITION p2000s VALUES IN (2000,2001,2002,2003,2004,2005,2006,2007,2008,2009) ENGINE = MyISAM, PARTITION p2010s VALUES IN (2010,2011,2012,2013,2014,2015,2016,2017,2018,2019) ENGINE = MyISAM) */;

--
-- Not keeping the _name fields for players; to restore them, add to schema above and remove the '@' below
--

LOAD DATA INFILE '/data/rawd/sports/baseball/retrosheet/game_logs-1871-2013.csv'
REPLACE INTO TABLE `games`
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY "\r\n"
IGNORE 1 ROWS
(
  game_dt,
  game_ct,
  game_day_of_week,
  away_team_id,
  away_lg_id,
  away_game_seq,
  home_team_id,
  home_lg_id,
  home_game_seq,

  away_runs_ct,
  home_runs_ct,
  tot_outs_ct,
  game_daynight,
  completion_info,
  forfeit_info,
  protest_info,
  park_id,
  @park_attendence,
  @game_minutes_ct,
  away_linescore,
  home_linescore,

  away_AB,
  away_H,
  away_D,
  away_T,
  away_HR,
  away_RBI,
  away_SH,
  away_SF,
  away_HBP,
  away_BB,
  away_IBB,
  away_K,
  away_SB,
  away_CS,
  away_GDP,
  away_CI,
  away_LOB,
  away_pit_ids,
  away_ER,
  away_TER,
  away_WP,
  away_balks,
  away_PO,
  away_A,
  away_E,
  away_passed,
  away_DB,
  away_TP,

  home_AB,
  home_H,
  home_D,
  home_T,
  home_HR,
  home_RBI,
  home_SH,
  home_SF,
  home_HBP,
  home_BB,
  home_IBB,
  home_K,
  home_SB,
  home_CS,
  home_GDP,
  home_CI,
  home_LOB,
  home_pit_ids,
  home_ER,
  home_TER,
  home_WP,
  home_balks,
  home_PO,
  home_A,
  home_E,
  home_passed,
  home_DB,
  home_TP,

  ump_H_id,
  @ump_H_name,
  ump_1B_id,
  @ump_1B_name,
  ump_2B_id,
  @ump_2B_name,
  ump_3B_id,
  @ump_3B_name,
  ump_LF_id,
  @ump_LF_name,
  ump_RF_id,
  @ump_RF_name,
  manager_away_id,
  @manager_away_name,
  manager_home_id,
  @manager_home_name,

  pit_win_id,
  @pit_win_name,
  pit_loss_id,
  @pit_loss_name,
  pit_save_id,
  @pit_save_name,
  bat_gwRBI_id,
  @bat_gwRBI_name,
  pit_away_start_id,
  @pit_away_start_name,
  pit_home_start_id,
  @pit_home_start_name,

  bat_away_1__id,
  @bat_away_1_name,
  bat_away_1_pos,
  bat_away_2__id,
  @bat_away_2_name,
  bat_away_2_pos,
  bat_away_3__id,
  @bat_away_3_name,
  bat_away_3_pos,
  bat_away_4__id,
  @bat_away_4_name,
  bat_away_4_pos,
  bat_away_5__id,
  @bat_away_5_name,
  bat_away_5_pos,
  bat_away_6__id,
  @bat_away_6_name,
  bat_away_6_pos,
  bat_away_7__id,
  @bat_away_7_name,
  bat_away_7_pos,
  bat_away_8__id,
  @bat_away_8_name,
  bat_away_8_pos,
  bat_away_9__id,
  @bat_away_9_name,
  bat_away_9_pos,

  bat_home_1__id,
  @bat_home_1_name,
  bat_home_1_pos,
  bat_home_2__id,
  @bat_home_2_name,
  bat_home_2_pos,
  bat_home_3__id,
  @bat_home_3_name,
  bat_home_3_pos,
  bat_home_4__id,
  @bat_home_4_name,
  bat_home_4_pos,
  bat_home_5__id,
  @bat_home_5_name,
  bat_home_5_pos,
  bat_home_6__id,
  @bat_home_6_name,
  bat_home_6_pos,
  bat_home_7__id,
  @bat_home_7_name,
  bat_home_7_pos,
  bat_home_8__id,
  @bat_home_8_name,
  bat_home_8_pos,
  bat_home_9__id,
  @bat_home_9_name,
  bat_home_9_pos,

  additional_info,
  acquisition_info
  )
  SET
    park_attendence = IF(@park_attendence = '', NULL, @park_attendence),
    game_minutes_ct = IF(@game_minutes_ct = '', NULL, @game_minutes_ct),
    game_id    = CONCAT(home_team_id, game_dt, game_ct),
    game_date = STR_TO_DATE(game_dt, "%Y%m%d"),
    -- game_time = STR_TO_TIME(game_dt, game_time), "%Y%m%d%H%M%S"),
    year_id    = LEFT(game_dt, 4)
  ;
