TODO: Intro
* What we want the reader to have learned
* Call forward to the section on advanced Pig

=== Group and Flatten

The fundamental Map/Reduce operation is to group a set of records and operate on that group.  In fact, it’s a one-liner in Pig:

----
BINS = Group WP_pageviews by (date, hour)
DESCRIBE BINS
(TODO:CODE: SHOW OUTPUT)
----

The result is always a tuple whose first field is named “Group” -- holding the individual group keys in order.  The next field has the full input record with all its keys, even the group key.  Here’s a Wukong script that illustrates what is going on:

----
(TODO:CODE: Wukong script)
----

You can group more than one dataset at the same time.  In weather data, there is one table listing the location and other essentials of each weather station and a set of tables listing, for each hour, the weather at each station.  Here’s one way to combine them into a new table, giving the explicit latitude and longitude of every observation:

----
G1=GROUP WSTNS BY (ID1, ID2), WOBS BY (ID1, ID2);
G2=FLATTEN G1…
G3=FOR EACH G2 …
----

This is equivalent to the following Wukong job:

----
(TODO:CODE: Wukong job)
----

(TODO: replace with an example where you would use a pure COGROUP).

====  Join Practicalities

The output of the Join job has one line for each discrete combination of A and B.  As you will notice in our Wukong version of the Join, the job receives all the A records for a given key in order, strictly followed by all the B records for that key in order.  We have to accumulate all the A records in memory so we know what rows to emit for each B record.  All the A records have to be held in memory at the same time, while all the B records simply flutter by; this means that if you have two datasets of wildly different sizes or distribution, it is worth ensuring the Reducer receives the smaller group first.  In Wukong, you do this by giving it an earlier-occurring field group label; in Pig, always put the table with the largest number of records per key last in the statement.

==== Ready Reckoner: How fast should your Pig fly?

TODO:CODE: describe for each Pig command what jobs should result.

====  More

There are a few more Operators we will use later in the book:
Cube, which produces aggregations at multiple levels within a Group;
Rank, which is sugar on top of Order to produce a number, total-ordered set of records;
Split, to separate a dataset into multiple pieces; and
Union, to produce a new dataset to have all the records from its input datasets.

That’s really about it.  Pig is an extremely sparse language.  By having very few Operators and very uniform syntax (FOOTNOTE:  Something SQL users but non-enthusiasts like your authors appreciate), the language makes it easy for the robots to optimize the dataflow and for humans to predict and reason about its performance.

We won’t spend any more time introducing Pig, the language, as its usage will be fairly clear in context as you meet it later in the book.  The online Pig manual at (TODO: REF) is quite good and for a deeper exploration, consult (TODO: Add name of best Pig book here).

==== Pig Gotchas

TODO:CODE: That one error where you use the dot or the colon when you should use the other.
TODO:CODE: Where to look to see that Pig is telling you have either nulls, bad fields, numbers larger than your type will hold or a misaligned schema.


// ------
// stream do |article|
//   words = Wukong::TextUtils.tokenize(article.text, remove_stopwords: true)
//   words.group_by(&:to_s).map{|word, occurs|
//     yield [article.id, word, occurs.count]
//   end
// end
// ------
//
// Reading it as prose the script says "for each article: break it into a list of words; group all occurrences of each word and count them; then output the article id, word and count."
//
// .Snippet from the Wikipedia article on "Barbecue"
// [quote, wikipedia, http://en.wikipedia.org/wiki/Barbeque]
// ____
// Each Southern locale has its own particular variety of barbecue, particularly concerning the sauce. North Carolina sauces vary by region; eastern North Carolina uses a vinegar-based sauce, the center of the state enjoys Lexington-style barbecue which uses a combination of ketchup and vinegar as their base, and western North Carolina uses a heavier ketchup base. Lexington boasts of being "The Barbecue Capital of the World" and it has more than one BBQ restaurant per 1,000 residents. In much of the world outside of the American South, barbecue has a close association with Texas. Many barbecue restaurants outside the United States claim to serve "Texas barbecue", regardless of the style they actually serve. Texas barbecue is often assumed to be primarily beef. This assumption, along with the inclusive term "Texas barbecue", is an oversimplification. Texas has four main styles, all with different flavors, different cooking methods, different ingredients, and different cultural origins. In the June 2008 issue of Texas Monthly Magazine Snow's BBQ in Lexington was rated as the best BBQ in the state of Texas. This ranking was reinforced when New Yorker Magazine also claimed that Snow's BBQ was "The Best Texas BBQ in the World".
// ____
//
// The output of the first stage
//
// ----
// 37135	texas   	8
// 37135	barbecue	8
// 37135	bbq     	5
// 37135	different	4
// 37135	lexington	3
// 37135	north   	3
// 37135	carolina	3
// ----
